### ISSUE TITLE
blender import tensorflow has error

### ISSUE THREAD

**Issue by myBestLove** [EugeniyStern/Blender_Tensorflow#1]
thx for your work

and I want to use tensorflow in blender,  so  I use pip install tensorflow , which pip belongs to blender' python.  when i import tensorflow , it works well ,  but if i create session,  it occur  segment  fault and blender exit automaticlly.   
Do you know how to solve this problem.   and can you share your version of tensorflow and blender and some configs.
thx

**Comment by EugeniyStern** [comment]
hello colleague,
I install tensorflow directly from anaconda, no blender pip.

I run this on:
Eclipse + PyDev
tf 1.7.0 Blender 2.79.

Also i can try to run it on second conf with cuda, but need some time. This is not my primary business.
Configuration with cuda support:

Standard Intel station 64, window 7 64 pro sp1
GeForce 1060 6 GB, cuda 9.0.176, blender 2.79

tensorflow 1.8.0
blender 2.79

hope, regards

**Comment by EugeniyStern** [comment]
TF runs separately from blender

**Comment by myBestLove** [comment]
thx for your answer.  now I trying to run tensorflow outside of blender
